# Generated by Django 4.2.20 on 2026-06-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batches',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.IntegerField()),
                ('raw_row', models.JSONField()),
                ('anomaly_type', models.CharField(choices=[('mixed_date_format', 'Mixed date format'), ('ambiguous_date', 'Ambiguous date'), ('exact_duplicate', 'Exact duplicate row'), ('conflicting_duplicate', 'Conflicting duplicate'), ('settlement_as_expense', 'Settlement logged as expense'), ('usd_amount', 'USD amount converted'), ('missing_currency', 'Missing currency'), ('amount_formatting', 'Amount formatting issue'), ('negative_amount', 'Negative amount (refund?)'), ('zero_amount', 'Zero amount'), ('inconsistent_name', 'Inconsistent member name'), ('missing_payer', 'Missing payer'), ('percentage_not_100', "Percentages don't sum to 100%"), ('split_type_mismatch', 'split_type/details mismatch'), ('non_member_in_split', 'Non-member in split_with'), ('member_outside_window', 'Member outside membership window'), ('excluded_participant', 'Participant excluded (not a registered member)')], max_length=50)),
                ('description', models.TextField()),
                ('applied_policy', models.TextField()),
                ('status', models.CharField(choices=[('auto_handled', 'Auto handled'), ('needs_review', 'Needs review'), ('resolved', 'Resolved')], default='auto_handled', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importbatch')),
                ('linked_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='expenses.expense')),
                ('linked_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='expenses.settlement')),
            ],
            options={
                'db_table': 'import_anomalies',
                'ordering': ['batch', 'source_row_number'],
            },
        ),
    ]
